### ISSUE TITLE
How to do compression on custom file?

### ISSUE THREAD

**Issue by aayush-gupta15** [mohit1997/DNA_Compression#15]
I have setup the noGPU version on my system but whenever i try to run run_experiments file for xor30 it starts training and training time is around 5 hours per epoc. How to use pretrained models to do compression.

**Comment by mohit1997** [comment]
Hi,

One simple way to use pretrained models for compression/decompression is to comment lines 49-52 in [install.sh](https://github.com/mohit1997/DeepZip/blob/master/src/run_experiments.sh). You can then run `bash run_experiments.sh` and then uncomment lines 49-52 and comment line 45 in [install.sh](https://github.com/mohit1997/DeepZip/blob/master/src/run_experiments.sh)

Note that pretrained model still has to be trained once. You can run it google collaboratory which provides free GPU and then download the model.

**Comment by kv304** [comment]
One additional question , can we use the trained weights(.hdf5 files) present in the repo somehow? Like suppose we trained the model on xor dataset , can we use the existing weights of this model to run compressor and decompressor on a random text file?

**Comment by mohit1997** [comment]
There are two problems with this, first is the different vocabulary size and second is the generalization. You can conduct this experiment on two different text files. You train the NN (Neural Network) model on file 1 and then compress file 2 with the saved model. Since the vocabulary would be the same, the NN model will accept the input from file 2, but might not generalize well and give relatively worse compression ratio for file 2. I suspect if your file 1 is large and file 2 is similar w.r.t file 1 in terms of how you obtained the data. For example, both files might be English texts from the same book. In this case, you might get better generalization and hence compress file 2 better.
