### ISSUE TITLE
do you want to have a C++ version

### ISSUE THREAD

**Issue by JsBlueCat** [mohit1997/DNA_Compression#8]
do you want to have a c++ version？
and does the sequence length affect the compress result？

**Comment by mohit1997** [comment]
Right now there are no plans for developing a C++ version. The sequence length does affect the compression results because of (i) the performance of the neural network does depend on the amount of training data  (The user can always increase the number of training epochs to improve performance) and (ii) if the sequence length is too small, the overhead of model size might negatively affect the overall compression performance.

**Comment by JsBlueCat** [comment]
> Right now there are no plans for developing a C++ version. The sequence length does affect the compression results because of (i) the performance of the neural network does depend on the amount of training data (The user can always increase the number of training epochs to improve performance) and (ii) if the sequence length is too small, the overhead of model size might negatively affect the overall compression performance.

so if i have a 4T file * 3 , need i to train 3 model to compress each?  or i need use one model to compress three files ? 
i mean does the deep learning performs well than gzip bz2 in mutlefiles ?
